pipeline{
agent{
    
    docker{
      image 'maven:latest'
      args '--entrypoint='
    }   
}
    parameters{
        choice(name:'tag', choices:['@regression','@integration'])
    }
    
stages{
    stage("dependance"){
        steps{
            dir ("demo"){
                
            sh 'mvn --version'
            sh 'mvn clean compile'
            }
        }
    }
    stage("execution"){
        steps{
            dir ("demo"){
            sh 'mvn test -Durl="https://www.saucedemo.com" -Dgroups="params.tag"';
        }}
    }
}


}
